server:
  port: 8080 # Porta padrão do Gateway (ponto de entrada)

eureka:
  instance: 
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # CORRETO: Aponta para o Eureka Server na porta 8761
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-catalog
        # lb => load balance
          uri: lb://PRODUCT-CATALOG
          predicates:
            - Path=/product/**
        - id: shopping-cart
          uri: lb://SHOPPING-CART
          predicates:
            - Path=/cart/**